title: David Alber
description: foo

image_base:  "/images"
date_format: "%b %-d, %Y"

header_pages:
 - about.md

permalink:    /:categories/:year/:month/:title/

plugins: [jekyll-paginate, jemoji]
paginate:     10
sass:
  compressed: true

exclude: ["Rakefile", "Gemfile", "Gemfile.lock", "make-tag-files.sh"]

google_analytics: "UA-110543077-1"
